import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import SearchExperience from '../components/SearchExperience';


const handleSearchSubmit = (searchText: string) => {
  // Perform search with searchText
  console.log('Search submitted with:', searchText);
};


export default function Home() {
  return (
    <>
      <Head>
        <title>Copilot Help Center Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1>Copilot Help Center Assistant</h1>
        <h2> This product lets you search the knowledge base of Copilot.</h2>

        <div>
          <SearchExperience onSubmit={handleSearchSubmit} />
        </div>
        
      </main>

    </>
  )
}

